# Generated by Django 3.0.2 on 2020-03-01 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=200, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарии в диалогах',
                'verbose_name_plural': 'Комментарии в диалогах',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Rom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название комноты')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v0.Room_comment', verbose_name='Комментарий')),
                ('user_invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invited', to=settings.AUTH_USER_MODEL, verbose_name='Гости')),
                ('user_main', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_main', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Диалоги пользователей',
                'verbose_name_plural': 'Диалоги пользователей',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=25, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=25, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=25, verbose_name='Отчество')),
                ('link', models.CharField(max_length=25, unique=True, verbose_name='Сылка')),
                ('img_caver', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Кавер')),
                ('img_avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Аватарка')),
                ('black_sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_sheet', to=settings.AUTH_USER_MODEL, verbose_name='Список врагов')),
                ('friends', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends_user', to='api_v0.Profile', verbose_name='Список друзей')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ('-id',),
            },
        ),
    ]
