# Generated by Django 3.0.2 on 2020-03-01 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_v0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='black_sheet',
        ),
        migrations.AddField(
            model_name='profile',
            name='black_sheet',
            field=models.ManyToManyField(null=True, related_name='black_sheet', to=settings.AUTH_USER_MODEL, verbose_name='Список врагов'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_profile_friends_+', to='api_v0.Profile', verbose_name='Список друзей'),
        ),
    ]
