# Generated by Django 3.0.2 on 2020-03-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0002_auto_20200301_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='black_sheet',
            field=models.ManyToManyField(blank=True, related_name='_profile_black_sheet_+', to='api_v0.Profile', verbose_name='Список врагов'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='api_v0.Profile', verbose_name='Список друзей'),
        ),
    ]
