# Generated by Django 3.0.2 on 2020-03-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v0', '0004_remove_profile_black_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='black_sheet',
            field=models.ManyToManyField(blank=True, related_name='_profile_black_sheet_+', to='api_v0.Profile', verbose_name='Список врагов'),
        ),
    ]
